---
title: "`r end_date`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# USB Distribution

```{r, warning=FALSE}

# usb_distribution <- read_csv("../data/usb_distribution.csv", na = "")
raw <- usb_distribution[, -c(1, 2, 4)]

trc <- trainControl(method = "cv", number = 10)
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "glm",
                family = binomial())  
paste0("LASSO overall error rate: ", 1 - logfit$results[, 2])
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "rpart")
paste0("CART overall error rate: ", 1 - logfit$results[1, 2])
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "rf",
                allowParallel = TRUE)
paste0("Random Forest overall error rate: ", 1 - logfit$results[1, 2])

```

# Web Distribution

```{r, warning=FALSE}

# web_distribution <- read_csv("../data/web_distribution.csv", na = "")
raw <- web_distribution[, -c(1,2,8)]
rc <- trainControl(method = "cv", number = 10)
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "glm",
                family = binomial(), na.action = na.exclude)  
paste0("LASSO overall error rate: ", 1 - logfit$results[, 2])
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "rpart")
paste0("CART overall error rate: ", 1 - logfit$results[1, 2])
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "rf",
                allowParallel = TRUE)
paste0("Random Forest overall error rate: ", 1 - logfit$results[1, 2])


```

# Logon Distribution

```{r, warning=FALSE}

# logon_distribution <- read_csv("../data/logon_distribution.csv", na = "")
raw <- logon_distribution[, -c(1, 2, 4)]
rc <- trainControl(method = "cv", number = 10)
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "glm",
                family = binomial(), na.action = na.exclude)  
paste0("LASSO overall error rate: ", 1 - logfit$results[, 2])
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "rpart")
paste0("CART overall error rate: ", 1 - logfit$results[1, 2])
logfit <- train(factor(attrition) ~ ., data = raw, trControl = trc, method = "rf",
                allowParallel = TRUE)
paste0("Random Forsest overall error rate: ", 1 - logfit$results[1, 2])


```

