---
title: "Project"
subtitle: "STAT5525: Data Analytics"
author: "Team"
date: "`r Sys.Date()`"
output: html_document
abstract: "This paper discusses the methods and results of various statistical learning techniques applied to unstructured data. We discuss our feature development and model performance in a business analytics setting."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction And Exploratory Analyses

Our data is spread across several different files with both unique and non-unique features within and across files. Information readily available to us are timestamps, PC ID, and user ID of PC logon and logoffs, HTTP traffic, and USB connections and disconnections. Additionally, we are given monthly employee data files consisting of the current employee roster complete with employee name, employee user ID, role, and employee email address. From this information we are able to infer employee attrition based on the most recent employee roster. It is important to note that for the user HTTP traffic, we only track up to 15 unique URLs during business hours and up to five unique URL after business hours.

We collated the logon, HTTP, and USB traffic into a new dataset to be more suitable for exploratory analyses and feature creation. The data was grouped into chronological order with other information such as user name, email, and attrition also included. Two initial obstacles were so-called "lonely" logons and USB connections. For a given user ID and PC, there were several instances of consecutive logons and USB connections. In the case of consecutive logons, this is the result of inactivity and the machine requiring user login after a certain period of inactivity. Unpaired logins occured between 11% to 14% of the time and varried slightly by user role. The IT administrators did this less frequently, about 1.5% of the time. For lonely USB connections, this is due to machines being shut down before the USB is disconnected. Unpaired USB connects were even less frequent, due to only 25% of the total users in the data having used USB devices. To resolve these issues, we calculated the average logon time and average USB connection time for each user and replaced the unpaired logons and connections with these average usage times as well as flagging the entry. 

Our initial instincts lead us to analyze the logon, HTTP, and USB traffic separately and note inconsistencies amongst all users and within user roles for each data. From these inconsistencies, we could further scrutinize specific users for these abnormal behaviors. Examples of abnormal behaviors include PC logon and logoff in under a minute, USB connect and disconnect in under a minute, and abnormal web traffic, such as visiting `facebook.com` over 500 times in a single working day. For instantaneous logons and logoffs across several machines, this could be indicative of a malicious bot. Similarly in the case of instantaneous USB connections across, this could idenfity installation of malicious software. USB connections after hours could also possibly idenfity a data breach. Excessive web traffic could also be an artifact of bot traffic or malware. 

